"""delete plusTwo

Revision ID: 4dc26a868633
Revises: 1af8a52e3cab
Create Date: 2025-10-19 22:44:05.192032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc26a868633'
down_revision: Union[str, Sequence[str], None] = '1af8a52e3cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solves', 'plusTwo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solves', sa.Column('plusTwo', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
