"""update user model

Revision ID: 7ec53fe30e54
Revises: eb0d5cc50477
Create Date: 2025-10-19 23:09:33.265739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec53fe30e54'
down_revision: Union[str, Sequence[str], None] = 'eb0d5cc50477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('imageUrl', sa.String(), nullable=True))
    op.drop_column('users', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'imageUrl')
    # ### end Alembic commands ###
