// 2-3 imageable words per Speffz pair, curated from https://www.speedsolving.com/wiki/index.php?title=List_of_letter_pairs
// (NSFW, filler and cubing-jargon entries dropped). JX and XX have no entry on the wiki.
export const PAIR_WORDS: Record<string, string> = {
  AA: "Aardvark / AA Batteries / American Airlines", AB: "Abacus / Abs / Ali Baba", AC: "Acorn / Air Conditioner / Ace",
  AD: "Adele / Advertisement / Adrenaline", AE: "Aeroplane / Aerosol Can / Amelia Earhart",
  AF: "Afro / Air Force / Africa", AG: "Agent / Ali G / Silver", AH: "Air Hockey / Air Horn / Anthony Hopkins",
  AI: "Artificial Intelligence / American Idol / Allen Iverson", AJ: "Apple Juice / Angelina Jolie / Ajax",
  AK: "AK-47 / Alicia Keys / Alaska", AL: "Alien / Alligator / Abraham Lincoln",
  AM: "Ambulance / Ammunition / Arctic Monkeys", AN: "Ant / Antenna / Aunt", AO: "Aorta / Aerosol / AOL",
  AP: "Apple / Ape / Austin Powers", AQ: "Aquarium / Antique / Aqua", AR: "Arrow / Arm / Alan Rickman",
  AS: "Astronaut / Ashtray / Adam Sandler", AT: "Atom / Atlas / AT-AT", AU: "Automobile / Australia / Gold",
  AV: "Avenue / Antonio Vivaldi / Audio Visual", AW: "Amy Winehouse / Awe", AX: "Axe / Axolotl / Axl Rose",
  BA: "Bagel / Batman / British Airways", BB: "Basketball / Blackberry / Breaking Bad",
  BC: "Bicycle / Bacon / Bill Clinton", BD: "Bed / Bass Drum / Beedrill", BE: "Bee / Belt / Beyonce",
  BF: "Bonfire / Butterfly / Bigfoot", BG: "Bag / Badge / Bee Gees", BH: "Beehive / Bath / Bahamas",
  BI: "Bird / Billiards / Billboard", BJ: "Blackjack / Billy Joel", BK: "Burger King / Book / Bike",
  BL: "Bell / Ball / Bull", BM: "Bob Marley / Bum", BN: "Banana / Bone / Bill Nye", BO: "Boat / Bottle / Barack Obama",
  BP: "Backpack / Brad Pitt / Ballpoint Pen", BQ: "Barbecue / Bouquet", BR: "Bear / Beer / Bar",
  BS: "Bass / Boss / Britney Spears", BT: "Boot / Bat / Boston Terrier", BU: "Bus / Bulb / Bull",
  BV: "Beaver / Boulevard", BW: "Bow / Bowling / Black Widow", BX: "Box / Boxer",
  CA: "Camera / Carrot / Cappuccino", CB: "Cube / Corn Cob / Christian Bale", CC: "Coconut / Calculator / Cop Car",
  CD: "Compact Disc / Cod / Cameron Diaz", CE: "Cement / Ceiling / Clint Eastwood", CF: "Coffee / Coffin / Cuffs",
  CG: "Cage / Cog / Cigarette", CH: "Chair / Cheerleader / Cher", CI: "Circus / Cigar / Cinema",
  CJ: "Cajon / Carl Johnson (GTA)", CK: "Cake / Cook / Calvin Klein", CL: "Clown / Clock / Clover",
  CM: "Camel / Comb / Cookie Monster", CN: "Cone / Can / Chuck Norris", CO: "Coyote / Coke / Cobalt",
  CP: "Cop / Cape / Chris Pratt", CQ: "Croquet / Conquest", CR: "Car / Cross / Cristiano Ronaldo",
  CS: "Castle / Chess / Cheese", CT: "Cat / Coat / Cot", CU: "Cup / Copper / Carrie Underwood", CV: "Cave / Clover",
  CW: "Cow / Christopher Walken", CX: "Coaxial Cable",
  DA: "Dagger / Dance / Dark Knight", DB: "Disco Ball / Dobby / David Blaine",
  DC: "Dice / Washington DC / David Copperfield", DD: "Dad / Dungeons & Dragons / Don Draper",
  DE: "Dentist / Denmark / Dean", DF: "Daffodils / Dolphin / Duffel Bag", DG: "Dog / Dig Dug / David Guetta",
  DH: "Dough / Dollhouse / Dustin Hoffman", DI: "Dinosaur / Disney / Digger", DJ: "DJ / Dwayne Johnson / Dojo",
  DK: "Duck / Donkey Kong / Duke", DL: "Doll / Dial / Dell", DM: "Dome / Dam / Darth Maul",
  DN: "Donut / Dungeon / Dune", DO: "Dolphin / Doe / Doom", DP: "Diaper / Dip / Dolly Parton",
  DQ: "Dairy Queen / Drag Queen / Dennis Quaid", DR: "Dragon / Doctor / Dr Pepper",
  DS: "Nintendo DS / Death Star / Dr. Seuss", DT: "Dart / Donald Trump / Date", DU: "Duck / Dunkin' Donuts / Duolingo",
  DV: "Darth Vader / Dove / DVD", DW: "Dwarf / Darkwing Duck / DreamWorks", DX: "Dexter / Deluxe",
  EA: "Eagle / EA Games", EB: "Eyeball / Easter Bunny / Emmett Brown", EC: "Eclair / Eclipse",
  ED: "Ed Sheeran / Mr. Ed / Edward (Twilight)", EE: "Eel / Eye", EF: "Elephant / Elf / Effie Trinket", EG: "Egg",
  EH: "Edward Hicks", EI: "Einstein / Eskimo", EJ: "Eject", EK: "Elk / EKG / Earthquake", EL: "Elf / Elvis / Elmo",
  EM: "Eminem / Emperor / Emo", EN: "Envelope / Ent / Entei", EO: "Eeyore", EP: "EpiPen / Epicurus",
  EQ: "Equator / Equestrian / Equation", ER: "Ear / Emergency Room", ES: "Eskimo / ESPN", ET: "E.T. / Eat",
  EU: "Europe / Euphonium / Eucalyptus", EV: "Eevee / Evil / Electric Vehicle", EW: "Ewe",
  EX: "Excalibur / Explosion / Ex",
  FA: "FIFA / Fat Albert", FB: "Football / Facebook", FC: "Face / 50 Cent / Fetch", FD: "Food / Fedora / FedEx Truck",
  FE: "Ferret", FF: "Firefighter / Free Fall", FG: "Frog / Fig / Fog", FH: "Fire Hydrant / Fish / Full House",
  FI: "Fiddle / Fish / Fight", FJ: "Fajita / Fiji", FK: "Fork", FL: "Flower / Flood / Flour", FM: "Foam / FM Radio",
  FN: "Fin / Fang / Fan", FO: "Fox / Fossil / Foil", FP: "Falcon Punch / Fireplace / Facepalm",
  FQ: "Lord Farquaad / FAQ", FR: "Fridge / Fruit / Fire", FS: "Fish", FT: "Foot / Boba Fett / Feet", FU: "Fugitive",
  FV: "Five", FW: "Ferris Wheel / Flower", FX: "Fox",
  GA: "Gargoyle / Gamble", GB: "Ghostbusters / Game Boy / Globe", GC: "GameCube / Guacamole",
  GD: "Godzilla / God / Geometry Dash", GE: "Genie / Gem / Gentleman", GF: "Giraffe / Girlfriend / GIF",
  GG: "Goggles / Google / Good Game", GH: "Ghost / Greenhouse / Gandhi", GI: "G.I. Joe / Gin / Ginny Weasley",
  GJ: "Green Giant / Grape Jelly / Grape Juice", GK: "Goku / Geek / Green Knight", GL: "Glass / Globe / Goal",
  GM: "Gum / Gem / Good Morning", GN: "Gun / Gondola / Gengar", GO: "Gold / Gorilla", GP: "Grapes / GPS / Gap",
  GQ: "GQ Magazine", GR: "Grass / Graduate / Green", GS: "Goose / Ghost / Gas", GT: "Goat", GU: "Guitar / Gull / Gun",
  GV: "Grave / Gravel", GW: "George Washington / Glow", GX: "Germ-X / Yu-Gi-Oh! GX",
  HA: "Harp / Harpoon", HB: "HB Pencil / Haribo / HBO", HC: "Helicopter / Hardcore", HD: "Hot Dog / Head",
  HE: "Helium / Hero / Herb", HF: "Hot Fudge / Half", HG: "Hagrid / Hermione Granger / Hug", HH: "Hedgehog / Fishhook",
  HI: "Hippo", HJ: "Heinz", HK: "Captain Hook / Hong Kong / Hook", HL: "Hill / Hell / Hugh Laurie",
  HM: "Hammer / Hummingbird / Hummer", HN: "Honey / Hen", HO: "House / Hose / Hoe", HP: "Harry Potter / HP",
  HQ: "Harley Quinn / Hockey / Headquarters", HR: "Heart / Hair / Hare", HS: "High School / Hose / Howard Stern",
  HT: "Hat / Hut", HU: "Hunter / Hummus", HV: "Hoverboard / Heaven", HW: "Homework / Hawk / Halloween",
  HX: "Hexagon / Helix / Hacksaw",
  IA: "Iowa / Ian", IB: "I-Beam / Ibis / Ibuprofen", IC: "Ice Cream / Icarus / Ice", ID: "ID Card / Idaho",
  IE: "Internet Explorer / Ice", IF: "Eiffel Tower / Infinity", IG: "Iguana / Igloo / Instagram",
  IH: "Incredible Hulk / IHOP", II: "II (Roman 2)", IJ: "Indiana Jones / Injection", IK: "IKEA / Ink",
  IL: "Island / Illinois", IM: "Iron Man / Imposter", IN: "Inch / Inn / Indiana", IO: "Iodine / Iowa",
  IP: "iPod / iPad", IQ: "IQ", IR: "Iron / Infrared / Iran", IS: "Ice Skates / Space Station",
  IT: "Iced Tea / It (clown) / Italy", IU: "ICU", IV: "Ivy / Ivysaur / Ivory Coast", IW: "Inchworm / Ice Water",
  IX: "Ibex / Ice Axe / Index",
  JA: "Jaguar / Jar / Jaws", JB: "James Bond / Jukebox / Justin Bieber", JC: "Jackie Chan / John Cena / Julius Caesar",
  JD: "Jedi / Jack Daniel's / Jordan", JE: "Jet Plane / Jet Engine", JF: "Jellyfish / JFK / Jif", JG: "Jug / Jaguar",
  JH: "Jabba the Hutt", JI: "Jigsaw Puzzle", JJ: "Jamba Juice", JK: "Joker / Jackknife / JFK",
  JL: "Jack-o'-Lantern / Jail / Jelly", JM: "Jam / Jamaica / Just Married", JN: "Jeans / Juggernaut", JO: "Joey / Joe",
  JP: "Jurassic Park / Jigglypuff / Jeep", JQ: "Jacques Cousteau / Johnny Quest / John Quincy Adams",
  JR: "Jackrabbit / Jack the Ripper / Jar", JS: "Jester / Jerry Springer / Bach", JT: "Jet",
  JU: "Jungle / Juggle / Juice", JV: "Javelin / Jive", JW: "Jaws / Jigsaw Puzzle",
  KA: "Kangaroo", KB: "Keyboard / Kebab / Kobe Bryant", KC: "KFC / Kurt Cobain / Kicks",
  KD: "Kid / Kraft Dinner / Kevin Durant", KE: "Ketchup / Key / Kelp", KF: "KFC", KG: "King Kong / Kindergarten",
  KH: "Keyhole / Burj Khalifa / DJ Khaled", KI: "Kite", KJ: "Knee-Jerk / Kylie Jenner", KK: "King Koopa",
  KL: "Kuala Lumpur", KM: "Kimono / Kermit the Frog / Komodo Dragon", KN: "Knight / Knife / Kennel",
  KO: "Koala / Knockout / Korea", KP: "Krabby Patty / K-Pop / King Koopa", KQ: "King & Queen / Kumquat",
  KR: "Kryptonite / Knight Rider", KS: "Kiss / KSI", KT: "Katana / Kitten / Kite", KU: "Kate Upton / Kuala Lumpur",
  KV: "Kevlar", KW: "Kiwi / Killer Whale", KX: "Kix Cereal",
  LA: "Lamp / Los Angeles", LB: "Lobster / Lab / La-Z-Boy", LC: "Locust / Lucifer / Lick", LD: "Ladder / Lid / Lead",
  LE: "Leopard / Leo / Leap", LF: "Leaf / Elf", LG: "Lego / Log / Lady Gaga", LH: "Lighthouse",
  LI: "Lion / Lips / Listerine", LJ: "LeBron James / Lodge", LK: "Lock / Liu Kang / Elk", LL: "Lollipop",
  LM: "Llama / Lamb / Lionel Messi", LN: "Lantern / Looney Tunes / Land", LO: "Lobster / London / Log",
  LP: "Laptop / Lapras / Loop", LQ: "Liquor", LR: "Lord of the Rings / Lemur / Liar",
  LS: "Lightsaber / Lasso / Luke Skywalker", LT: "Lettuce / Lieutenant / Lottery", LU: "Lute / Luau / Lunchables",
  LV: "Lava / Lord Voldemort / Leaves", LW: "Lawnmower / Lil Wayne", LX: "Lexus / Laxative",
  MA: "Magikarp / Mail", MB: "Men in Black / Mercedes-Benz / Mob", MC: "Minecraft / Magician / MC Hammer",
  MD: "Mountain Dew / Mud / Mad Max", ME: "Middle-earth / Mass Effect / Maine", MF: "Muffin / Megaphone / Earmuffs",
  MG: "Magnet / Magazine / Mega Man", MH: "Manhole / Mohican / Miami Heat",
  MI: "Milk / Mission Impossible / Monsters, Inc.", MJ: "Michael Jackson / Michael Jordan / Mary Jane",
  MK: "Monkey / Mickey Mouse / Mary Kay", ML: "Mona Lisa / Mole / Millennium Falcon", MM: "Megaminx / Mom",
  MN: "Moon / Money / Manager", MO: "Moose / Mole / Molasses", MP: "Mop / Map / Max Park",
  MQ: "Mosquito / Mannequin / Masquerade Mask", MR: "Mermaid / Mars / Monorail", MS: "Mouse / Moss / Microsoft",
  MT: "Mountain / Minotaur / Mittens", MU: "Mushroom / Mule / Mustard", MV: "Minivan / Music Video / Max Verstappen",
  MW: "Mew / Meowth / Mace Windu", MX: "Mixer / Maximus / Malcolm X",
  NA: "Nacho / NASCAR / North America", NB: "Notebook / Nutter Butter / Nuts & Bolts", NC: "Necktie / Nyan Cat / Nacho",
  ND: "Needle / Ned Stark / Nancy Drew", NE: "Neon / Knee / Neo", NF: "Knife / Nerf / Niagara Falls",
  NG: "Chicken Nuggets / Eggnog / Noggin", NH: "Nursing Home / Neighborhood / NHL Hockey", NI: "Nike / Nile / Nickel",
  NJ: "Ninja / New Jersey / Navajo", NK: "Nuke / Nike / North Korea", NL: "Nail / Noodles / Night Light",
  NM: "Necromancer / Nicki Minaj / Nematode", NN: "Nun", NO: "Nose / Gnome / Noose", NP: "North Pole / Nap",
  NQ: "Nerf Football / NASDAQ", NR: "Nerd / Nori / Nair", NS: "Nest / Nintendo Switch / Noose", NT: "Net / Knot / Gnat",
  NU: "Nut / Nuclear", NV: "Navy / Nevada / Knave", NW: "Narwhal / Newt / Nuclear Waste", NX: "Knicks / Nixon",
  OA: "Oatmeal / Oar", OB: "Obelisk / Obama", OC: "Octopus / Ocarina / Orange County", OD: "Oddish / One Direction",
  OE: "Oboe / Oreo", OF: "Officer / Outfielder / Office", OG: "Ogre / Orange", OH: "One Hand", OI: "Oil / Oink (pig)",
  OJ: "Orange Juice / O.J. Simpson", OK: "Obi-Wan Kenobi", OL: "Olive", OM: "Ohm / Oatmeal / Om (monk chant)",
  ON: "Onion", OO: "Ooze", OP: "Opera / Oprah / Soda Pop", OQ: "Orc / Old Quill", OR: "Oreo / Oar / Orange",
  OS: "Ostrich", OT: "Otter / Oliver Twist / Old Testament", OU: "Ouija Board / Orangutan", OV: "Oven",
  OW: "Owl / Owen", OX: "Ox / Oxygen",
  PA: "Paper Airplane / Paprika / Pam Anderson", PB: "Polar Bear / Peanut Butter / Lead", PC: "Peacock / Popcorn / PC",
  PD: "Panda / Pond / Police Department", PE: "Penguin / Peanut / Peru", PF: "Pirate Flag / PDF",
  PG: "Piggy Bank / Pig / Peter Griffin", PH: "Pharaoh / pH", PI: "Pie / Pier / Pi", PJ: "Pyjamas",
  PK: "Pikachu / Ice Pick / Puck", PL: "Pliers / Pluto", PM: "Pram / Pomegranate / Pyraminx",
  PN: "Peter Pan / Pen / Penny", PO: "Postman / Post Office / Poop", PP: "Pepperoni Pizza / Philadelphia Phillies",
  PQ: "Porcupine / Patchwork Quilt", PR: "Predator / Pear / Prius",
  PS: "PlayStation / Pencil Sharpener / Postage Stamp", PT: "Pterodactyl / Pet", PU: "Puma / Puddle / Punisher",
  PV: "Pole Vault / PVC Pipe", PW: "Paw / Power / POW", PX: "Pickaxe / Pixel",
  QA: "Quail / Quartz / Quarter", QB: "Quarterback / Cubie", QC: "Quick / Quinceanera / Quaich",
  QD: "Quidditch / Qdoba / Cutie", QE: "Queen Elizabeth / Queen / Queue", QF: "Quaffle / Quake Fiend",
  QG: "Qui-Gon Jinn / Quagmire", QH: "Don Quixote / Quiche / Quahog", QI: "Quill / Qi Energy", QJ: "Squeegee",
  QK: "Quaker Oats / Quark", QL: "Quail / Quill", QM: "Quasimodo / Quagmire / Queen Mary",
  QN: "Harley Quinn / Quinoa / Queen", QO: "Quaker Oats / Qui-Gon Jinn", QP: "Quarter Pounder / Quip",
  QQ: "Quartz / Qashqai", QR: "QR Code / Qatar / Riddick", QS: "Quicksand / Quicksilver / Quesadilla",
  QT: "Q-Tip / Cutie / Quarantine", QU: "Queen / Queue / Quarry", QV: "Quiver", QW: "QWERTY Keyboard / Nesquik",
  QX: "Qix / Quicksand",
  RA: "Rabbit / Raccoon / Race Car", RB: "Robocop / Rhubarb / Root Beer", RC: "Rubik's Cube / Race Car / Rice",
  RD: "Rubber Duckie / Road Runner / Rod", RE: "Reese's / Ren (Ren & Stimpy)", RF: "Referee / Roof / Raft",
  RG: "Rug / Rag / Balrog", RH: "Rhino / Right Hand / Rohan", RI: "Riddler / Rhino / Rice", RJ: "RJ45 Cable / Reject",
  RK: "Rake / Rock / Rick Astley", RL: "Red Lobster / Roller Skates / Railing", RM: "Ram / Rome / Rum",
  RN: "Nurse / Rain / Raisins", RO: "Rook / Rope / Rock", RP: "Rapper / Rope / Rip", RQ: "Racquet / Racquetball",
  RR: "Railroad", RS: "Rose / Rust / Ross (Friends)", RT: "Rat / Ritz Crackers", RU: "Roulette / Ruby / Ruxpin",
  RV: "RV / Raven / River", RW: "Ron Weasley / Ringwraith / Row", RX: "T-Rex / Pharmacy",
  SA: "Saw / Satellite / Salvation Army", SB: "Submarine / Sabertooth / Sub", SC: "Scorpion / Sock / Soccer",
  SD: "Scooby-Doo / Star Destroyer / Sled", SE: "Sea / Sesame Seed / Semaphore", SF: "San Francisco / Surf / Safe",
  SG: "Segway / Stargate", SH: "Ship / Sheep / Stonehenge", SI: "Sink / Satellite / Silicone",
  SJ: "Slim Jim / Steve Jobs / Sage", SK: "Skeleton / Ski / Sock", SL: "Seal / Slime",
  SM: "Smokey the Bear / Smoke / Sam-I-Am", SN: "Sonic / Snail / Snow", SO: "Sofa / Soap / Soda",
  SP: "Spaghetti / Sap / Soap", SQ: "Squirrel / Square-1 / Sasquatch", SR: "Syringe / Sriracha / Star",
  SS: "ShengShou / Speedsolving", ST: "Star / Statue / Santa", SU: "Sun / Sugar / Steve Urkel",
  SV: "SUV / Sven / Seven", SW: "Swan / Swing / Subway", SX: "Saxophone / Sound Effects",
  TA: "Tank / Taco", TB: "Table / Tuba / Time Bomb", TC: "Tic Tac / Taco / Tick", TD: "Toad / Tadpole / Teddy Bear",
  TE: "Tent / Telephone / Tea", TF: "TIE Fighter / Transformer / Taffy", TG: "Tiger / Tigger / Trigger", TH: "Thor",
  TI: "Tire / TIE Fighter / Tile", TJ: "Trojan Horse / Thomas Jefferson", TK: "Truck / Tack",
  TL: "Turtle / Troll / Tail", TM: "Tin Man / Timpani / Trademark", TN: "TNT / Tin / Tin Man", TO: "Tomb / Toe",
  TP: "Toilet Paper / Tepee / Top", TQ: "Tequila / Taquitos", TR: "Tree / Train / Tarantula",
  TS: "Tsunami / Toast / Tom Sawyer", TT: "Tooth / Tutu / Tater Tots", TU: "Tuxedo / Tutu / Tub", TV: "Television",
  TW: "Towel / Tower / Tow Truck", TX: "Texas / Tux / Taxes",
  UA: "United Airlines / Under Armour", UB: "U-Boat / Usain Bolt / Umbrella", UC: "Unicorn / UCLA", UD: "Udder",
  UE: "Ukulele", UF: "UFO", UG: "Uggs / Ugly", UH: "U-Haul Truck / Frankenstein", UI: "Unicycle",
  UJ: "Jerome Eugene Morrow (Gattaca)", UK: "United Kingdom / Ukulele / Ukraine", UL: "Ulysses S. Grant",
  UM: "Umbrella", UN: "Uno / Underwear / Universe", UO: "Yu-Gi-Oh / Duo", UP: "UPS Truck / Up (in the sky)",
  UQ: "Urquhart Castle / Uruk-hai", UR: "Urine", US: "Uncle Sam / Zeus / United States", UT: "Undertaker / Utah",
  UU: "Yo-Yo", UV: "Ultraviolet / Hoverboard", UW: "Underwater", UX: "Tuxedo",
  VA: "V8 / Vaporizer", VB: "Volleyball", VC: "Vacuum / V-Cube", VD: "Video / Voodoo", VE: "Vending Machine / Vent",
  VF: "Venus Flytrap", VG: "Vegas / Vegetables", VH: "VHS Tape / Van Helsing / Van Halen", VI: "Visor / Visa",
  VJ: "Virgil", VK: "Viking", VL: "Vial / Vlad (Dracula) / Vole", VM: "Venom / Vomit / Vending Machine",
  VN: "Van / Violin", VO: "Volcano", VP: "Vampire / VIP / Vape", VQ: "Ventriloquist", VR: "Virtual Reality",
  VS: "Vase / Vise", VT: "Vault / Vet / Vote", VU: "Vulture", VV: "Volvo / V-2 Rocket", VW: "Volkswagen",
  VX: "Vortex / Vixen",
  WA: "Whale / Water / Wallaby", WB: "Web / Warner Bros / Wobbuffet", WC: "Witch / Bathroom",
  WD: "WD-40 / Wood / Wedding Dress", WE: "Welder / Weed", WF: "Waffle / Waterfall / Waffle Fries", WG: "Wig",
  WH: "Whip / Whistle / Wheat", WI: "Wii / Wine / Wire", WJ: "Ouija Board / Potato Wedges", WK: "Wok / Wookiee",
  WL: "Wall / Well", WM: "Watermelon / Worm / Walmart", WN: "Window", WO: "Werewolf", WP: "Weapons / Whip",
  WQ: "Wicker / Watch", WR: "Wizard / Wrench / World Record", WS: "Walrus / Wasabi", WT: "Water Tower / Weights",
  WU: "Wormtongue / Wu-Tang Clan", WV: "Wave / Weaver", WW: "Willy Wonka / WWE", WX: "Wax / Windex",
  XA: "Xavier (X-Men) / Electrocuted Alligator / A-Team", XB: "Beast (X-Men) / Electrocuted Bulbasaur",
  XC: "Cyclops (X-Men) / Electrocuted Charizard / X-Acto Knife", XD: "Electrocuted Diglett / XD Emoticon",
  XE: "Electric Eel / Xenon", XF: "Electrocuted Fox / Phantom of the Opera",
  XG: "Gambit (X-Men) / Electrocuted Gorilla", XH: "Helicopter",
  XI: "Xylophone / Iceman (X-Men) / Electrocuted Ivysaur", XJ: "Jubilee (X-Men) / Juggernaut (X-Men) / Jaguar XJ220",
  XK: "Electrocuted Kangaroo / Genghis Khan", XL: "Extra Large / Sauron / Electrocuted Lapras",
  XM: "Magneto (X-Men) / X-Mas / Xenomorph", XN: "Nightcrawler (X-Men)", XO: "Storm (X-Men) / Tic-Tac-Toe",
  XP: "Windows XP / Electrocuted Pikachu / Python", XQ: "Shaq / Quicksilver (X-Men) / Electrocuted Queen",
  XR: "X-Ray / Rogue (X-Men) / Electrocuted Raichu", XS: "Spider-Man / Electrocuted Snorlax / Spider",
  XT: "Terminator / Electrocuted Turtle", XU: "Uruk-hai / Electrocuted Unicorn", XV: "Electrocuted Venusaur",
  XW: "Wolverine (X-Men) / X-Wing / Crossword",
};
